package com.example.rest;



import javax.ws.rs.core.MediaType;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.example.Entity.User;
import com.example.service.Userservice;

@RestController
@Component
@CrossOrigin

public class UserController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private Userservice userService;
	
	
	@RequestMapping(method = RequestMethod.POST, value="/login",produces = MediaType.APPLICATION_JSON) // This means URL's start with /api (after Application path)
	
	public  ResponseEntity<User> addNewUser (@RequestBody User user) {
		
		try {
		
		User usr = userService.findByEmailIgnoreCaseAndPassword(user);
		usr.setPassword(null);
		return new ResponseEntity<User>(usr,HttpStatus.OK);
		}
		catch(Exception e) {
			throw new RuntimeException(e);
		}
		 
	}
	
	@RequestMapping(method = RequestMethod.POST, value="/delete",produces = MediaType.APPLICATION_JSON) // This means URL's start with /api (after Application path)
	
	public HttpStatus deleteuser (@RequestBody User user) {
		
		try {
		
		userService.deletebyuser(user);
		return HttpStatus.OK;
		}
		catch(Exception e) {
			throw new RuntimeException(e);
		}
		 
	}
	

}
